### PR TITLE
Bugfix/fixsanityrulesmovement

### PR DESCRIPTION
**Pull request by gregoryrinaldi**
- fix for validation of incoming positions not being evaluated correctly

### CODE REVIEW

**Review by ebrygg — COMMENTED** [review]
I am really curious about the performance implications of the implementation of the below method:

private KieSession getKieSession()

Doesn't it cost a lot to create this on every eval of a positition?

**Comment by gregoryrinaldi** [comment]
It is handled by drools it self.
To gain something we need to use the drools stateless session but it will come at a cost. For the moment we need the state look at FactRuleEvaluator line 160.

**Review by ebrygg — APPROVED** [review]
ok then, lets do some tests on this.

**Comment by gregoryrinaldi** [comment]
Hugo will send some positions now to test will let you know the results

**Pull request merged**
