### PR TITLE
Bel dev

### PR DESCRIPTION
**Pull request by stainii**
Make it possible to receive and send FLUX messages for the Sales module.

### CODE REVIEW

**Comment by stainii** [comment]
Please test me

**Comment by stainii** [comment]
Please test me

**Comment by stainii** [comment]
Please test me

**Comment by stainii** [comment]
Build success! Finally!

**Comment by stainii** [comment]
Thanks for the review. @AdityaPadhy, could your team have a look at the Fishing Activity/Rules engine portion?

**Comment by stainii** [comment]
Changes, asked by @ebrygg, are implemented. Along with some extra rules for Sales.
In order to make the build succeed, can this pull requesst be merged first? https://github.com/UnionVMS/UVMS-RulesModule-MODEL/pull/9

**Comment by ebrygg** [comment]
Yes, go ahead.
/ Andreas
On Tue, Jun 27, 2017 at 12:56, Stijn Hooft  wrote: Changes, asked by @ebrygg (https://github.com/ebrygg), are implemented. Along with some extra rules for Sales.
 In order to make the build succeed, can this pull requesst be merged first? UnionVMS/UVMS-RulesModule-MODEL#9 (https://github.com/UnionVMS/UVMS-RulesModule-MODEL/pull/9)

**Comment by stainii** [comment]
please test me

**Pull request merged**
