### PR TITLE
Bug/change rules to use date for mdr lists

### PR DESCRIPTION
**Pull request by ankovi**
1. Cleaned MdrCacheService and related bean definition from deprecated methods.
2. Change rule_init.xml in order to use the mdr related methods which check also the validity date.
3. MDR cache now will be loaded only when needed and not automatically each hour.
    Only when needed = MDR codelists were updated.

4. Stijn could you please confirm the change to the SalesRulesServiceBean.java bean?

### CODE REVIEW

**Comment by gregoryrinaldi** [comment]
test me

**Comment by ankovi** [comment]
test me

**Comment by ankovi** [comment]
test me

**Review by stainii — APPROVED** [review]
Got a thorough explanation of Andi how the code works. This is certainly an improvement in comparison with how it worked before.

I think some parts could be extracted to other classes to make the whole more readable.

Also, since multiple modules have a cache of MDR, a more higher-level architectural approach could be searched to solve this problem.

Nevertheless, given the current time pressure, this is an adaquate solution.

**Comment by ankovi** [comment]
@stainii 

Absolutely.. it can follow the same architectural principles of AbstractConfigSettingsBean..

**Comment by stainii** [comment]
I wasn't thinking about AbstractConfigSettingsBean, but more at JMS level.

It would be nice if the MDR module would publish changes on a **topic**. Other modules (like Rules, Sales, Assets, who keep a cache of MDR), can listen to this topic and take in changes.

Then there is no need to query MDR every x time, making the code less complex.

Something that's definitely high on my wishlist, when we have more room to breathe.

**Comment by gregoryrinaldi** [comment]
ok that is a bigger change

**Pull request merged**
