### PR TITLE
GitHub Synchronization with the latest from DG-MARE

### PR DESCRIPTION
**Pull request by gkgeorgiev**

### CODE REVIEW

**Comment by Ozsie** [comment]
test this please

**Comment by Ozsie** [comment]
@gkgeorgiev Activity and MDR models are missing from FOCUS nexus.

[ERROR] Failed to execute goal on project rules-service: Could not resolve dependencies for project eu.europa.ec.fisheries.uvms.rules:rules-service:ejb:3.0.0-SNAPSHOT: The following artifacts could not be resolved: eu.europa.ec.fisheries.uvms.activity:activity-model-fa:jar:0.5.5, eu.europa.ec.fisheries.uvms.mdr:mdr-model:jar:0.5.0-SNAPSHOT, eu.europa.ec.fisheries.uvms.rules:rules-model:jar:2.1.3-SNAPSHOT, eu.europa.ec.fisheries.uvms.activity:activity-model:jar:0.5.7-SNAPSHOT: Could not find artifact eu.europa.ec.fisheries.uvms.activity:activity-model-fa:jar:0.5.5 in focus-releases (http://nexus.focus.fish/nexus/content/repositories/releases/)

**Comment by gkgeorgiev** [comment]
test this please

**Comment by Ozsie** [comment]
test this please

**Comment by Ozsie** [comment]
test this please

**Comment by gkgeorgiev** [comment]
hopefully this is the last Sync issue

**Comment by Ozsie** [comment]
test this please

**Pull request merged**
