### PR TITLE
Improvement/make rules great again

### PR DESCRIPTION
**Pull request by ankovi**

### CODE REVIEW

**Comment by ankovi** [comment]
* Yet another improvement on MDR cache. Now when we have a lot of messages coming in it will make the getRefreshDateFrom to MDR moduleonly in a "reasonable" manner. (Example not when sending a response).

* Changed the way the drools engine is initialized, in order to have a synchronized manner of validating each message but underneath with a "parallel" validating meccanism (check MasterEvaluator class).
Now each type of message will have it's own drools KieContainer to check the rules against :)
This way each KieContainer is lighter and faster.

* Totally new checkRulesAreDeployed function which is way faster then the "canary" it was before.

* Still the sequenced way of dealing with messages is kept. In a Singleton if @Lock and Locktype are not specified then the default value is LockType.WRITE.

* Refactoring.

* Typical timing for evaluating a FaReportMessage has dropped from more then 10 seconds to between 0.7 - 2 seconds, depending on the load of the machine.

**Comment by ankovi** [comment]
test me

**Comment by gregoryrinaldi** [comment]
test me

**Review by gregoryrinaldi — COMMENTED** [review]
awesome!

**Pull request merged**
