### PR TITLE
remove throw

### PR DESCRIPTION
**Pull request by gregoryrinaldi**

### CODE REVIEW

**Comment by stainii** [comment]
Why?

**Comment by ebrygg** [comment]
That looks weird, this will throw away the current message with no other trace than error messages in the log? Is this by design?

**Comment by gregoryrinaldi** [comment]
Guys what do you think about the logging of the errors because the only thing we get now is something like:

2018-07-04 01:52:12,902 INFO  [stdout] (default-threads - 27) 2018-07-03 23:52:08.105 [default-threads - 27]  ERROR e.e.e.f.u.r.service.bean.RulesEngineBean - Unable to validate facts. Reason: null

**Comment by stainii** [comment]
I propose to solve your problem by configuring the redelivery mechanism in a way that the frequency and amount of retries is minimized. This can be done in the code, example: RulesSalesReportEventConsumerBean.

If you really stand your ground on your opinion that the redelivery mechanism is a bad thing, please don't disable it for everyone in code, but disable it at server level. http://magnus-k-karlsson.blogspot.com/2013/08/configure-redelivery-for-activemq-58.html. That way, no one else is impacted.

About the log improvements, what's logged now is useless, indeed. Having more context would be helpful. I did not have the chance to test this code, yet, but what it's meant to do is promising.

**Comment by gregoryrinaldi** [comment]
We are currently doing test on this version do you approve it like it is?

**Comment by stainii** [comment]
FLUX expects an answer within 5 minutes. A 10 minute delay is not useful, 1 minute would be more useful.

**Comment by gregoryrinaldi** [comment]
But Stijn what if you have a queue of 1000 messages in rules it will take more then 5 minutes. Let's put it 5 minutes then

**Comment by gregoryrinaldi** [comment]
Is it ok like that for everyone?

**Comment by stainii** [comment]
If you set it to anything larger than 4 minutes, you'll create a situation in which a message that is redelivered to never be answered to in time. Why not try to do it in time? 

I'd rather have 3 retries, every minute, with a chance that the response gets back in time. Seems more useful to me than retrying a message whose answer will never arrive in time and is therefore useless.

**Comment by gregoryrinaldi** [comment]
fair enough

**Review by stainii — APPROVED** [review]

**Pull request merged**
